name: Template Acme Fitness Infrastructure Deploy
on:
    workflow_call:        
      inputs:
        NAME_PREFIX: 
            required: true
            type: string
        ENVIRONMENT: 
            required: true
            type: string
        REGION:
            required: true
            type: string
        TFSTATE_RG:
            required: true
            type: string
        STORAGEACCOUNTNAME:
            required: true
            type: string
        CONTAINERNAME:
            required: true
            type: string
        AZURE_CLIENT_ID:
          required: true
          type: string
        AZURE_SUBSCRIPTION_ID:
          required: true
          type: string
        AZURE_TENANT_ID:
          required: true
          type: string
        SPRING_APPS_SERVICE_NAME:
          required: true
          type: string
        SPRING_APPS_RG:
          required: true
          type: string
        PRIVATE_DNS_RG:
          required: true
          type: string
        SPOKE_RG:
          required: true
          type: string
        SHARED_RG:
          required: true
          type: string
        DEPLOY_ASSISTANT:
          required: true
          type: string
      secrets:
        AZURE_CLIENT_SECRET:
            required: true
      outputs:
        openai_endpoint:
          value: ${{jobs.deploy_acme_fitness_assistant_infra.outputs.openai_endpoint}}
        openai_key:
          value: ${{jobs.deploy_acme_fitness_assistant_infra.outputs.openai_key}}
      
env:
    SPRING_APPS_SERVICE_NAME: ${{ inputs.SPRING_APPS_SERVICE_NAME}}
    SPRING_APPS_RG: ${{ inputs.SPRING_APPS_RG}}
    PRIVATE_DNS_RG: ${{ inputs.PRIVATE_DNS_RG }}
    SPOKE_RG: ${{inputs.SPOKE_RG}}
    SHARED_RG: ${{ inputs.SHARED_RG}}
    TFSTATE_RG: ${{inputs.TFSTATE_RG}}
    STORAGEACCOUNTNAME: ${{inputs.STORAGEACCOUNTNAME}}
    CONTAINERNAME: ${{ inputs.CONTAINERNAME}}
    NAME_PREFIX: ${{inputs.NAME_PREFIX}}
    ENVIRONMENT: ${{inputs.ENVIRONMENT}}
    REGION: ${{ inputs.REGION }}

    # ==== Terraform Azure Login ===:
    ARM_CLIENT_ID: ${{ inputs.AZURE_CLIENT_ID }} 
    ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
    ARM_SUBSCRIPTION_ID: ${{ inputs.AZURE_SUBSCRIPTION_ID }}
    ARM_TENANT_ID: ${{ inputs.AZURE_TENANT_ID }}
jobs:
    deploy_acme_fitness_infra:
        name: ACME Fitness Store Infrastructure
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: Scenarios/sample-apps/fitness-store/terraform
        steps:
        - name: Checkout this repository
          uses: actions/checkout@v3
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v2.0.3
          with:
            terraform_wrapper: false
        - name: Terraform Init
          run: |
            terraform init \
            -backend-config="resource_group_name=${{ env.TFSTATE_RG }}" \
            -backend-config="storage_account_name=${{ env.STORAGEACCOUNTNAME }}" \
            -backend-config="container_name=${{ env.CONTAINERNAME }}"
        - name: Terraform Plan
          run: |
            terraform plan -out my.plan \
            -var="spring_cloud_service=${{ env.SPRING_APPS_SERVICE_NAME}}" \
            -var="name_prefix=${{ env.NAME_PREFIX }}" \
            -var="private_zones_resource_group_name=${{ env.PRIVATE_DNS_RG }}" \
            -var="resource_group=${{ env.SPOKE_RG }}" \
            -var="subscription_id=${{ env.ARM_SUBSCRIPTION_ID}}" \
            -var="spring_cloud_resource_group_name=${{ env.SPRING_APPS_RG }}" \
            -var="shared_rg=${{ env.SHARED_RG }}"
        - name: Terraform Apply
          run: terraform apply my.plan
    deploy_acme_fitness_assistant_infra:
        name: ACME Fitness Store Assistant Infrastructure
        runs-on: ubuntu-latest
        needs: deploy_acme_fitness_infra
        if: inputs.DEPLOY_ASSISTANT
        outputs:
          openai_endpoint: ${{steps.output.outputs.openai_endpoint}}
          openai_key: ${{ steps.output.outputs.openai_key}}
        defaults:
            run:
                working-directory: Scenarios/sample-apps/fitness-store-assistant/terraform
        steps:
        - name: Checkout this repository
          uses: actions/checkout@v3
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v2.0.3
          with:
            terraform_wrapper: false
        - name: Terraform Init
          run: |
            terraform init \
            -backend-config="resource_group_name=${{ env.TFSTATE_RG }}" \
            -backend-config="storage_account_name=${{ env.STORAGEACCOUNTNAME }}" \
            -backend-config="container_name=${{ env.CONTAINERNAME }}"
        - name: Terraform Plan
          run: |
            terraform plan -out my.plan \
            -var="spring_cloud_service=${{ env.SPRING_APPS_SERVICE_NAME}}" \
            -var="name_prefix=${{ env.NAME_PREFIX }}" \
            -var="private_zones_resource_group_name=${{ env.PRIVATE_DNS_RG }}" \
            -var="spoke_resource_group_name=${{ env.SPOKE_RG }}" \
            -var="spring_cloud_resource_group_name=${{ env.SPRING_APPS_RG }}" \
            -var="shared_rg_name=${{ env.SHARED_RG }}"
        - name: Terraform Apply
          run: terraform apply my.plan
        - name: Terraform Output
          id: output
          run: |
            echo openai_endpoint=$(terraform output -raw openai_endpoint) >> $GITHUB_OUTPUT
            echo openai_key=$(terraform output -raw openai_key) >> $GITHUB_OUTPUT
