name: Deploy cart service
on:
    workflow_call:
        inputs:
            SUBSCRIPTION_ID:
                required: true
                type: string
            ASA_SERVICE_NAME:
                required: true
                type: string
            ASA_RG:
                required: true
                type: string
        secrets:
            AZURE_CREDENTIALS:
                required: true
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
          with:
            repository: Azure-Samples/acme-fitness-store.git
            path: fitness-store
            ref: Azure
        - name: Set up Azure
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        - name: Set up Azure Spring Extension
          run: |
            az extension add --name spring 
            az account set --subscription ${{ inputs.SUBSCRIPTION_ID }} 
            az configure --defaults group=${{ inputs.ASA_RG}} spring=${{inputs.ASA_SERVICE_NAME}} 
        - name: Lookup Staging Deployment Name
          run: |
            echo "STAGING_APP=$(az spring app deployment list --resource-group ${{ inputs.ASA_RG}} --service "${{inputs.ASA_SERVICE_NAME}}" --app frontend --query "[?properties.active==\`false\`].name" --output tsv)" >> $GITHUB_ENV
        - name: Deploy Cart service
          run: |
            az account set --subscription ${{ inputs.SUBSCRIPTION_ID }}
            az spring app deploy \
                --name "cart-service" \
                --resource-group ${{ inputs.ASA_RG}} \
                --service "${{inputs.ASA_SERVICE_NAME}}" \
                --deployment $STAGING_APP \
                --env "CART_PORT=8080" \
                --source-path "${{ github.workspace }}/fitness-store/apps/acme-cart"
        - name: Test Staging Deployment
          run: |
            echo "Testing Staging Endpoint"
        - name: Active Staging Deployment
          run: |
            az spring app set-deployment \
                --name "cart-service" \
                --deployment $STAGING_APP 